name: Psalm

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  style:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']
        setup: ['stable']

    name: PHP ${{ matrix.php }} - ${{ matrix.setup }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: psalm-${{ runner.os }}-${{ matrix.setup }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          psalm-${{ runner.os }}-${{ matrix.setup }}-${{ matrix.php }}-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      # tests/use-fork.php because of https://github.com/vimeo/psalm/issues/8957
      run: |
        php tests/use-fork.php vimeo/psalm 5.14.2 https://github.com/kylekatarnls/psalm.git fix/datetime-inheritance-5.x
        composer update --prefer-dist ${{ matrix.setup != 'next' && format('--prefer-{0}', matrix.setup) || '' }} --no-progress

    - name: Check style with psalm
      run: composer run-script psalm
